"""Keep generated scan artifacts for the latest five KRX sessions."""
import argparse
from copy import deepcopy
from datetime import date, datetime, timedelta, timezone
import json
from pathlib import Path
import re

import exchange_calendars


def retention_cutoff(as_of):
    day = date.fromisoformat(as_of)
    calendar = exchange_calendars.get_calendar(
        'XKRX', start=day - timedelta(days=60), end=day)
    return calendar.sessions[-5].strftime('%Y%m%d')


def cleanup_artifacts(root, as_of, dry_run=False):
    root = Path(root).resolve()
    cutoff = retention_cutoff(as_of)
    print(f'[CLEANUP] Keep five KRX sessions from {cutoff} (as of {as_of})')

    def safe(path):
        return not path.is_symlink() and path.resolve().is_relative_to(root)

    def expired(value):
        try:
            datetime.strptime(value, '%Y%m%d')
        except ValueError:
            return False
        return value < cutoff

    history_path = root / 'scan_history.json'
    history = {}
    if history_path.exists() and safe(history_path):
        history = json.loads(history_path.read_text(encoding='utf-8'))
    retained = deepcopy({d: rows for d, rows in history.items() if not expired(d)})
    candidates = set()
    codes = set()

    def collect_codes(value):
        if isinstance(value, dict):
            chart = value.get('chart', '')
            match = re.fullmatch(r'charts/(\d{8})/[^/]+', chart)
            if match and expired(match[1]):
                value['chart'] = ''
            if 'code' in value:
                codes.add(str(value['code']))
            for child in value.values():
                collect_codes(child)
        elif isinstance(value, list):
            for child in value:
                collect_codes(child)

    collect_codes(retained)
    scanner = root / 'cloud_scanner'
    for folder in (root, scanner):
        for path in folder.glob('scan_results_*_????????.json'):
            if not safe(path):
                continue
            stamp = path.stem.rsplit('_', 1)[-1]
            if expired(stamp):
                candidates.add(path)
            else:
                collect_codes(json.loads(path.read_text(encoding='utf-8')))
        for path in folder.glob('*.pdf'):
            # Only reports generated by the scanners, not arbitrary documents.
            if re.fullmatch(r'(?:김일청의_(?:양음양기법(?:_v2전략)?|포도시차트)|이동평균선과_500억봉_및_150억봉_분석보고서)_\d{8}(?:_\d{6})?\.pdf', path.name):
                stamp = re.search(r'_(\d{8})(?:_\d{6})?\.pdf$', path.name)[1]
                if expired(stamp):
                    candidates.add(path)

    old_dirs = []
    for charts in (root / 'charts', scanner / 'charts'):
        if not safe(charts):
            continue
        for folder in charts.glob('*'):
            if folder.is_dir() and safe(folder) and expired(folder.name):
                old_dirs.append(folder)
                candidates.update(p for p in folder.rglob('*') if p.is_file() and safe(p))
    # Undated charts are scratch copies; date-specific public copies live in charts/YYYYMMDD.
    for path in (scanner / 'charts').glob('*.png'):
        if re.fullmatch(r'[0-9A-Za-z]{6}', path.stem) and path.stem not in codes:
            candidates.add(path)

    deleted = []
    for path in sorted(candidates):
        if safe(path):
            relative = str(path.relative_to(root))
            print(f'[CLEANUP] {"Would delete" if dry_run else "Delete"}: {relative}')
            if not dry_run:
                path.unlink()
            deleted.append(relative)
    if not dry_run:
        for folder in old_dirs:
            # Remove only empty directories after the individually checked files.
            dirs = sorted((p for p in folder.rglob('*') if p.is_dir()), reverse=True)
            for path in dirs + [folder]:
                if safe(path) and not any(path.iterdir()):
                    path.rmdir()
        if retained != history:
            history_path.write_text(json.dumps(retained, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'[CLEANUP] {len(deleted)} files; history dates: {sorted(retained)}')
    return deleted


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--as-of', default=datetime.now(timezone(timedelta(hours=9))).date().isoformat())
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()
    cleanup_artifacts(Path(__file__).resolve().parent, args.as_of, args.dry_run)
